title: Code
theme: minima
markdown: kramdown
logo: /assets/images/logo.png

url: https://multum-non-multa.github.io
baseurl: /code
# relative_url: <== not sure this is proper config yaml

author: multum-non-multa
  # name: "multum-non-multa"
  # email: nomailtaken@email.com
description: > # this means to ignore newlines until "show_excerpts:"

show_excerpts: false # set to true to show excerpts on the homepage


# pages in nav bar
# header_pages:
#   - about
#   - resources



# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  multum-non-multa
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings

# plugins:
# - jekyll-asset-path-plugin
# - jekyll-feed
# - jekyll-seo-tag
